//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    // Generated by `pnpm run typegen`, not hand-written source.
    ignores: ['adk/**', 'src/lib/adk-types.d.ts'],
  },
]
