//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    // Generated by `pnpm run typegen`, not hand-written source.
    // storybook-static is the `build-storybook` output.
    ignores: ['adk/**', 'src/lib/adk-types.d.ts', 'storybook-static/**'],
  },
]
